name: Shutter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53712
title: Home is where the art is
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f6'
    - '#baad9e'
    - '#1f1a16'
    - '#6c6055'
    - '#6194c3'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
