name: Shutter
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcb3a3'
    - '#362f3f'
    - '#fdf5eb'
    - '#716149'
    - '#c92c35'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
